name: MLflow Training

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install pandas numpy scikit-learn mlflow==2.19.0

      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local
